name: Release

on:
  release:
    types:
      - published

env:
  DATA_URL: ${{ secrets.DATA_URL }}
  SOURCE_DIRECTORY: ${{ secrets.SOURCE_DIRECTORY }}
  OUTPUT_DIRECTORY: ${{ secrets.OUTPUT_DIRECTORY }}
  TRANSFORMED_DIRECTORY: ${{ secrets.TRANSFORMED_DIRECTORY }}

jobs:
  database_build:
    name: Build medicines database
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6.1.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: nicksettler/cz-dlp:${{ github.event.release.tag_name }}
          target: database
          build-args: |
            "DATA_URL=${{ secrets.DATA_URL }}"
            "SOURCE_DIRECTORY=${{ secrets.SOURCE_DIRECTORY }}"
            "OUTPUT_DIRECTORY=${{ secrets.OUTPUT_DIRECTORY }}"
            "TRANSFORMED_DIRECTORY=${{ secrets.TRANSFORMED_DIRECTORY }}"
