name: Release

on:
  release:
    types:
      - published
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string

env:
  DATA_URL: ${{ secrets.DATA_URL }}
  SOURCE_DIRECTORY: ${{ secrets.SOURCE_DIRECTORY }}
  OUTPUT_DIRECTORY: ${{ secrets.OUTPUT_DIRECTORY }}
  TRANSFORMED_DIRECTORY: ${{ secrets.TRANSFORMED_DIRECTORY }}

jobs:
  database_build:
    name: Build medicines database
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set release tag
        id: set_release_tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "RELEASE_TAG=${{ inputs.release_tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Print release tag
        run: |
          echo "RELEASE_TAG=${{ steps.set_release_tag.outputs.RELEASE_TAG }}"

      - name: Build and push
        uses: docker/build-push-action@v6.1.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: nicksettler/cz-dlp:${{ steps.set_release_tag.outputs.RELEASE_TAG }}
          target: database
          build-args: |
            "DATA_URL=${{ secrets.DATA_URL }}"
            "SOURCE_DIRECTORY=${{ secrets.SOURCE_DIRECTORY }}"
            "OUTPUT_DIRECTORY=${{ secrets.OUTPUT_DIRECTORY }}"
            "TRANSFORMED_DIRECTORY=${{ secrets.TRANSFORMED_DIRECTORY }}"
