name: Check for new data

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:

env:
  DATA_URL: ${{ secrets.DATA_URL }}

jobs:
    check_for_new_data:
        name: Check for new data
        runs-on: ubuntu-latest
        outputs:
          result: ${{ steps.set_result.outputs.result }}
        steps:
          - uses: actions/checkout@v3

          - name: Add GitHub repo
            run: |
              touch .env
              echo "GITHUB_REPO=${{ github.repository }}" >> .env

          - name: Setup bun
            uses: oven-sh/setup-bun@v1
            with:
              bun-version: latest

          - name: Install dependencies
            run: bun install

          - name: Check for new data
            id: check_for_new_data
            run: |
              set -e
              npm run run:check
              echo "exitcode=$?" >> $GITHUB_OUTPUT

          - name: Set result
            if: failure() || success()
            id: set_result
            run: |
              if [ ${{ steps.check_for_new_data.outputs.exitcode }} -eq 0 ]; then
                echo "result=success" >> $GITHUB_OUTPUT
              else
                echo "result=failure" >> $GITHUB_OUTPUT
              fi

    create_new_release:
      name: Create new release
      runs-on: ubuntu-latest
      needs: check_for_new_data
      if: needs.check_for_new_data.outputs.result == 'success'
      steps:
        - uses: actions/checkout@v3

        - name: Setup bun
          uses: oven-sh/setup-bun@v1
          with:
            bun-version: latest

        - name: Install dependencies
          run: bun install

        - name: Get latest version
          id: get_latest_version
          run: |
            echo "version=$(bun run run:get-version)" >> $GITHUB_OUTPUT

        - name: Create release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{ steps.get_latest_version.outputs.version }}

