name: Check for new data

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:

env:
  DATA_URL: ${{ secrets.DATA_URL }}

jobs:
    check_for_new_data:
        name: Check for new data
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Add GitHub repo
            run: |
              touch .env
              echo "GITHUB_REPO=${{ github.repository }}" >> .env

          - name: Setup bun
            uses: oven-sh/setup-bun@v1
            with:
              bun-version: latest

          - name: Install dependencies
            run: bun install

          - name: Check for new data
            id: check_for_new_data
            run: |
              npm run run:check
              echo "exitcode=$?" >> $GITHUB_OUTPUT

          - name: Get latest version
            id: get_latest_version
            continue-on-error: true
            run: |
              echo "version=$(bun run run:get-version)" >> $GITHUB_OUTPUT

          - name: Create release
            if: steps.check_for_new_data.outputs.exitcode == 1
            uses: softprops/action-gh-release@v2
            continue-on-error: true
            with:
              tag_name: ${{ steps.get_latest_version.outputs.version }}
